### ISSUE TITLE
Update iOS lib version please

### ISSUE THREAD

**Issue by TheWirv** [SelligentMarketingCloud/MobileSDK-ReactNative#20]
This package ships with v2.3.1 of the iOS lib. I also see `libSelligentMobile2.4.a` in the iOS directory, but `getVersionLib()` returns 2.3.1, which doesn't support iOS 14. Please update the integrated lib to the most recent v2.5.0 so that we can also profit from the most up-to-date features and bug fixes.

**Comment by MarcBiosca** [comment]
should be fixed now

**Comment by TheWirv** [comment]
> should be fixed now

@MarcBiosca Yes, you updated the lib version, that's true. But it is still only on 2.4, which is roughly 3.5 months old and, as I mentioned, does not support iOS 14. Could you please deploy a version that bundles **v2.5.0**?

**Comment by MarcBiosca** [comment]
@TheWirv A partner from us is owning the wrappers and they are quarterly updated (cost assumed by us) unless there is some issue that needs to be fixed, or if a client has a specific need then it can also be updated upon request (it has cost for you then).
SDK 2.4 has not any issue with IOS14 (2.4.1 was built with xcode 12 only, but nothing specific for that OS version was needed to be changed) and the changes since then are little bug fixes and exposing the IAM contents when sent separately from a push.
Are you noticing any issue with 2.4 when building/running though?

If you need any of the mentioned changes I would suggest you reach to your TPM/CSM about this to address it properly.

**Comment by TheWirv** [comment]
@MarcBiosca Fair enough, I didn't know it's that complicated behind the scenes. I guess this has to make do then. Regarding your question: No, no issues so far. But I also wouldn't like to run into any in the future because I am using an old package, that's all.

But as I said, all good. v2.1.2 will do it then.

**Comment by MarcBiosca** [comment]
OK! Fyi we will update the wrappers again before end of the year with latest SDKs (still to be planned the exact date)
